### ISSUE TITLE
IBM Websphere and Nodejs Connectivity

### ISSUE THREAD

**Issue by olindasequeira** [markusberg/ltpa#3]
Hi Markus,

Im working on a Nodejs app and it connects to REST API's sitting on IBM websphere application. The API's need the LTPA token for authorisation. Could you let me know if in this scenario, this package will work and what are the configurations required for it to work ?

Thanks so much!!
Olinda

**Comment by markusberg** [comment]
Hi,

it depends on what version of Websphere you're using, and how it has been configured. This package only supports LTPA1, and *not* LTPA2. WebSphere Application Server Version 5 and later supports LTPA1. WebSphere Application Server Version 7 and later supports LTPA2:
https://www.ibm.com/support/knowledgecenter/en/SSAW57_8.5.5/com.ibm.websphere.nd.doc/ae/cwbs_ltpatokens.html

I have never worked with Websphere myself (only Lotus Domino/Notes which uses the same LTPA-standards), so I'm unable to help you with your configuration. :disappointed: 

Best of luck

 / Markus

**Comment by benkroeger** [comment]
@olindasequeira I just published the first version of my [oniyi-ltpa](https://github.com/benkroeger/oniyi-ltpa) tools. as of now they cover basic operations for LTPA2 tokens.

they read the exported ltpa keys from websphere and would then be able to decode an existing token as well as generate new tokens from whatever bod you provide.

there is also code in there to decode LTPA1 tokens but creating those seems to be more challenging due to the rsa mode required for signing not being available in node.

**Comment by markusberg** [comment]
Nice job @benkroeger. I've updated my README.md with more information about ltpa versions, added a link to oniyi-ltpa, and pushed a patch-release.
